[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.29.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["ci"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Where to host releases
hosting = "github"

# Extra artifacts to include in release archives
[[dist.extra-artifacts]]
artifacts = [
  "man/man1/git-perf.1",
  "man/man1/git-perf-add.1",
  "man/man1/git-perf-audit.1",
  "man/man1/git-perf-bump-epoch.1",
  "man/man1/git-perf-list-commits.1",
  "man/man1/git-perf-measure.1",
  "man/man1/git-perf-prune.1",
  "man/man1/git-perf-pull.1",
  "man/man1/git-perf-push.1",
  "man/man1/git-perf-remove.1",
  "man/man1/git-perf-report.1",
  "docs/manpage.md"
]
build = ["./scripts/generate-manpages.sh"]
