# Test TOML file with asterisk in name and config values
[database]
host = "localhost"
port = 5432
name = "test_db"

[api]
base_url = "https://api.example.com"
timeout = 30

# Config value with asterisk in the middle
[special_config]
test_value_with_asterisk = "value*with*asterisk"
another_asterisk_value = "config*test*value"
normal_value = "regular_value"