name: 'Install git-perf'
description: 'Install git-perf binary'
inputs:
  release:
    description: 'release to install'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - id: latest-release
      name: determine latest release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        # TODO(kaihowl) how to not hard code?
        repository: kaihowl/git-perf
        excludes: prerelease, draft
    - id: install
      run: |
        mkdir -p ~/.git-perf/
        pushd ~/.git-perf

        if [ "${{ runner.os }}" = "Linux" ]; then
          os="x86_64-unknown-linux-musl"
        elif [ "${{ runner.os }}" = "macOS" ]; then
          os="x86_64-apple-darwin"
        else
          echo "Unsupported OS"
          exit 1
        fi

        if [[ "${{ inputs.release }}" == "latest" ]]; then
          release=${{ steps.latest-release.outputs.release }}
        else
          release=${{ inputs.release }}
        fi

        gitperf_url="https://github.com/kaihowl/git-perf/releases/download/${release}/gitperf-${release}-${os}.tar.gz"

        echo "Downloading and installing ${gitperf_url}"

        curl -L "$gitperf_url" | tar -xz --strip-components=1

        echo "$HOME/.git-perf" >> $GITHUB_PATH
      shell: bash
