name: 'Install git-perf'
description: 'Install git-perf binary'
inputs:
  release:
    description: 'release to install'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - id: install
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/kaihowl/git-perf/releases/download/v0.15.3/git-perf-installer.sh | sh
        export PATH=$HOME/.cargo/bin:$PATH
        git-perf --help
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash
