name: 'git-perf report'
description: 'git-perf report, upload to GitHub pages, and comment on PR'
inputs:
  release:
    description: 'release to install'
    required: false
    default: 'latest'
runs:
  using: "composite"
  concurrency: gh-pages-concurrency # keep_files==True uses last writer wins
  runs-on: ubuntu-22.04
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 40
