name: 'Cleanup git-perf Measurements and Reports'
description: 'Remove old measurements and orphaned reports from git-perf tracking'
author: 'Kai Höwelmeyer'

branding:
  icon: 'trash-2'
  color: 'orange'

inputs:
  retention-days:
    description: 'Number of days to retain measurements (e.g., 90)'
    required: false
    default: '90'
  backup:
    description: 'Create backup of measurements before removal'
    required: false
    default: 'true'
  cleanup-reports:
    description: 'Also cleanup orphaned reports on gh-pages branch'
    required: false
    default: 'true'
  git-perf-version:
    description: 'Version of git-perf to use (latest, or specific version)'
    required: false
    default: 'latest'
  dry-run:
    description: 'Perform dry-run without making actual changes'
    required: false
    default: 'false'
  reports-subdirectory:
    description: 'Subdirectory within gh-pages containing reports (must match report action)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set Git user and email
      shell: bash
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Install git-perf
      if: ${{ inputs.git-perf-version != 'skip' }}
      shell: bash
      run: |
        latest=""
        version=""
        if [ "${{ inputs.git-perf-version }}" = "latest" ]; then
          latest="latest/"
        else
          version="${{ inputs.git-perf-version }}/"
        fi
        download_url="https://github.com/kaihowl/git-perf/releases/${latest}download/${version}git-perf-installer.sh"
        echo "Downloading $download_url"
        curl --proto '=https' --tlsv1.2 -LsSf "$download_url" | sh
        export PATH=$HOME/.cargo/bin:$PATH
        git-perf --help
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Fetch performance notes
      shell: bash
      run: |
        # Fetch the notes ref to access measurements
        git fetch origin refs/notes/perf-v3:refs/notes/perf-v3 || echo "No notes ref found"

    - name: Create backup of measurements
      if: inputs.backup == 'true' && inputs.dry-run == 'false'
      shell: bash
      run: |
        # Create a backup of measurements before removal
        # This allows recovery if needed
        if git rev-parse --verify refs/notes/perf-v3 >/dev/null 2>&1; then
          git push origin refs/notes/perf-v3:refs/notes/perf-v3-backup --force
          echo "Backup created at refs/notes/perf-v3-backup"
        else
          echo "No measurements to backup"
        fi

    - name: Remove old measurements
      shell: bash
      run: |
        # Remove measurements older than specified retention period
        # git perf remove automatically pushes updated measurements
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          echo "[DRY-RUN] Would remove measurements older than ${{ inputs.retention-days }} days"
          git perf remove --older-than ${{ inputs.retention-days }}d --dry-run || echo "No measurements to remove or not applicable"
        else
          git perf remove --older-than ${{ inputs.retention-days }}d || echo "No measurements to remove or not applicable"
        fi

    - name: Fetch gh-pages branch
      if: inputs.cleanup-reports == 'true'
      shell: bash
      run: |
        git fetch origin gh-pages:gh-pages || echo "No gh-pages branch found"

    - name: Cleanup orphaned reports
      if: inputs.cleanup-reports == 'true'
      shell: bash
      env:
        REPORTS_SUBDIR: ${{ inputs.reports-subdirectory }}
      run: |
        # Run cleanup script to remove reports without measurements
        # Use -y flag for non-interactive execution in CI
        # Pass subdirectory via environment variable
        if [ -f ./scripts/cleanup-reports.sh ]; then
          chmod +x ./scripts/cleanup-reports.sh
          if [ "${{ inputs.dry-run }}" = "true" ]; then
            echo "[DRY-RUN] Would cleanup orphaned reports"
            if [ -n "$REPORTS_SUBDIR" ]; then
              echo "  in subdirectory: $REPORTS_SUBDIR"
            fi
            ./scripts/cleanup-reports.sh --dry-run || echo "Cleanup script failed but continuing"
          else
            if [ -n "$REPORTS_SUBDIR" ]; then
              echo "Cleaning up reports in subdirectory: $REPORTS_SUBDIR"
            fi
            ./scripts/cleanup-reports.sh -y || echo "Cleanup script failed but continuing"
          fi
        else
          echo "Cleanup script not found, skipping report cleanup"
        fi

    - name: Push gh-pages changes
      if: inputs.cleanup-reports == 'true' && inputs.dry-run == 'false'
      shell: bash
      run: |
        if git rev-parse --verify gh-pages >/dev/null 2>&1; then
          # Save current branch and set up trap to restore it on exit
          ORIGINAL_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          trap "git checkout '$ORIGINAL_BRANCH'" EXIT

          git checkout gh-pages
          if [ -n "$(git status --porcelain)" ]; then
            git push origin gh-pages
            echo "Pushed cleanup changes to gh-pages"
          else
            echo "No orphaned reports to clean up"
          fi
        else
          echo "No gh-pages branch, skipping report cleanup push"
        fi
