.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH add 1  "add " 
.SH NAME
add \- Add single measurement
.SH SYNOPSIS
\fBadd\fR <\fB\-m\fR|\fB\-\-measurement\fR> [\fB\-k\fR|\fB\-\-key\-value\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIVALUE\fR> 
.SH DESCRIPTION
Add single measurement
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-measurement\fR \fI<NAME>\fR
Name of the measurement
.TP
\fB\-k\fR, \fB\-\-key\-value\fR \fI<KEY_VALUE>\fR
Key\-value pairs separated by \*(Aq=\*(Aq
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVALUE\fR>
Measured value to be added
