.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH config 1  "config " 
.SH NAME
config \- Show configuration information including current branch and config file locations
.SH SYNOPSIS
\fBconfig\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show configuration information including current branch and config file locations
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
