.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH push 1  "push " 
.SH NAME
push \- Publish performance results to remote
.SH SYNOPSIS
\fBpush\fR [\fB\-r\fR|\fB\-\-remote\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Publish performance results to remote
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-remote\fR \fI<REMOTE>\fR
Remote to push to (defaults to git\-perf\-origin)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
