.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bump-epoch 1  "bump-epoch " 
.SH NAME
bump\-epoch \- Accept HEAD commit\*(Aqs measurement for audit, even if outside of range. This is allows to accept expected performance changes. This is accomplished by starting a new epoch for the given measurement. The epoch is configured in the git perf config file. A change to the epoch therefore has to be committed and will result in a new HEAD for which new measurements have to be taken
.SH SYNOPSIS
\fBbump\-epoch\fR <\fB\-m\fR|\fB\-\-measurement\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Accept HEAD commit\*(Aqs measurement for audit, even if outside of range. This is allows to accept expected performance changes. This is accomplished by starting a new epoch for the given measurement. The epoch is configured in the git perf config file. A change to the epoch therefore has to be committed and will result in a new HEAD for which new measurements have to be taken
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-measurement\fR \fI<MEASUREMENTS>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
