.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH prune 1  "prune " 
.SH NAME
prune \- Remove all performance measurements for non\-existent/unreachable objects. Will refuse to work if run on a shallow clone
.SH SYNOPSIS
\fBprune\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove all performance measurements for non\-existent/unreachable objects. Will refuse to work if run on a shallow clone
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
