name: ci

# TODO(kaihowl) deeper test with merge-based PR workflow (HEAD == merge commit)
# TODO(kaihowl) clean up old reports / do we want commit based reports anyway?

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  pull-requests: write

on:
  push:
    branches:
      - master
      - build/*
  pull_request:
    branches:
      - master
jobs:
  test:
    name: test
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - stable
        - beta
        include:
        - build: stable
          os: ubuntu-22.04
          rust: stable
        - build: beta
          os: ubuntu-22.04
          rust: beta
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 40

    - name: Set Git user and email
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}

    - name: Install libfaketime
      run: |
        if [[ $(uname -s) = Darwin ]]; then
          brew install libfaketime
        else # ubuntu
          sudo apt-get install libfaketime
        fi

    - name: Build git-perf
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run sample perf measurements
      run: |
          set -x
          cargo install --path git_perf
          # Run report on repo with known (n=10) number of measurements
          git perf measure -n 10 -m test-measure2 -k os=${{matrix.os}} -k rust=${{matrix.rust}} -- sleep 0.01
          git perf measure -n 10 -m report -k os=${{matrix.os}} -k rust=${{matrix.rust}} -- git perf report -n 1 -o report.html
          git perf add -m report-size -k os=${{matrix.os}} -k rust=${{matrix.rust}} $(wc -c < report.html)
          git perf push

          git perf audit -n 40 -m test-measure2 -s os=${{matrix.os}} -s rust=${{matrix.rust}} --min-measurements 10
          git perf audit -n 40 -m report -s os=${{matrix.os}} -s rust=${{matrix.rust}} --min-measurements 10
          git perf audit -n 40 -m report-size -s os=${{matrix.os}} -s rust=${{matrix.rust}} --min-measurements 10

    - name: Archive report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        include-hidden-files: true
        name: report-${{matrix.os}}-${{matrix.rust}}.html
        path: report.html
        if-no-files-found: error

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all --check

  clippy:
    name: clippy
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - name: Run clippy
      run: cargo clippy -- -D warnings

  rustdoc:
    name: rust doc
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt
    - name: Check docs
      run: |
        export RUSTDOCFLAGS="-D warnings"
        cargo doc --no-deps

  manpage-check:
    name: manpage check
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Install pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc
    - name: Build project to generate manpages and markdown
      run: |
        # Temporarily set version to 0.0.0 to avoid version-based diffs
        sed -i 's/^version = "[0-9]\+\.[0-9]\+\.[0-9]\+"/version = "0.0.0"/' git_perf/Cargo.toml
        cargo build
        # Restore original version
        git checkout -- git_perf/Cargo.toml
    - name: Check manpages are up to date
      run: |
        # Define expected manpage files (explicit list to avoid globbing issues)
        expected_files=(
          "target/man/man1/git-perf.1"
          "target/man/man1/git-perf-add.1"
          "target/man/man1/git-perf-audit.1"
          "target/man/man1/git-perf-bump-epoch.1"
          "target/man/man1/git-perf-measure.1"
          "target/man/man1/git-perf-prune.1"
          "target/man/man1/git-perf-pull.1"
          "target/man/man1/git-perf-push.1"
          "target/man/man1/git-perf-remove.1"
          "target/man/man1/git-perf-report.1"
        )
        
        # Check that all expected files exist
        missing_files=()
        for file in "${expected_files[@]}"; do
          if [[ ! -f "$file" ]]; then
            missing_files+=("$file")
          fi
        done
        
        # Check for unexpected files (new subcommands that aren't in our list)
        unexpected_files=()
        for file in target/man/man1/git-perf*.1; do
          if [[ -f "$file" ]]; then
            # Check if this file is in our expected list
            found=false
            for expected_file in "${expected_files[@]}"; do
              if [[ "$file" == "$expected_file" ]]; then
                found=true
                break
              fi
            done
            if [[ "$found" == "false" ]]; then
              unexpected_files+=("$file")
            fi
          fi
        done
        
        # Report any issues
        if [[ ${#missing_files[@]} -gt 0 ]]; then
          echo "Error: Missing manpage files:"
          printf '%s\n' "${missing_files[@]}"
          exit 1
        fi
        
        if [[ ${#unexpected_files[@]} -gt 0 ]]; then
          echo "Error: Unexpected manpage files found (new subcommands?):"
          printf '%s\n' "${unexpected_files[@]}"
          echo "Please update the expected_files array in .github/workflows/ci.yml to include these new files."
          exit 1
        fi
        
        # Generate complete manpage from current build (including all subcommands)
        for file in "${expected_files[@]}"; do
            echo "$(basename "$file" .1)";
            echo "================";
            pandoc -f man -t gfm "$file";
            echo -e "\n\n";
        done > /tmp/generated_manpage.md
        
        # Compare with existing manpage
        if ! diff -u docs/manpage.md /tmp/generated_manpage.md > /tmp/manpage.diff; then
          echo "Error: Manpage is out of date. A patch file has been created and will be uploaded as an artifact."
          echo ""
          echo "To fix this, you can either:"
          echo "1. Run the manpage generation command from README.md:"
          echo "   for file in target/man/man1/git-perf.1 target/man/man1/git-perf-add.1 target/man/man1/git-perf-audit.1 target/man/man1/git-perf-bump-epoch.1 target/man/man1/git-perf-measure.1 target/man/man1/git-perf-prune.1 target/man/man1/git-perf-pull.1 target/man/man1/git-perf-push.1 target/man/man1/git-perf-remove.1 target/man/man1/git-perf-report.1; do"
          echo "       echo \"\$(basename \"\$file\" .1)\";"
          echo "       echo \"================\";"
          echo "       pandoc -f man -t gfm \"\$file\";"
          echo "       echo -e \"\\n\\n\";"
          echo "   done > docs/manpage.md"
          echo ""
          echo "2. Or apply the patch file from the CI artifacts:"
          echo "   patch docs/manpage.md < manpage.diff"
          exit 1
        fi
        echo "Manpages are up to date ✓"
    - name: Check markdown is up to date
      run: |
        # Check that the generated markdown file exists
        if [[ ! -f "docs/manpage.md" ]]; then
          echo "Error: Generated markdown documentation not found at docs/manpage.md"
          exit 1
        fi
        
        # Create a backup of the original file for comparison
        cp docs/manpage.md /tmp/original_markdown.md
        
        # Temporarily set version to 0.0.0 to avoid version-based diffs
        sed -i 's/^version = "[0-9]\+\.[0-9]\+\.[0-9]\+"/version = "0.0.0"/' git_perf/Cargo.toml
        cargo build
        # Restore original version
        git checkout -- git_perf/Cargo.toml
        
        # Compare with the newly generated version
        if ! diff -u /tmp/original_markdown.md docs/manpage.md > /tmp/markdown.diff; then
          echo "Error: Markdown documentation is out of date. A patch file has been created and will be uploaded as an artifact."
          echo ""
          echo "To fix this, run:"
          echo "   cargo build"
          echo ""
          echo "The markdown documentation is automatically generated during the build process."
          exit 1
        fi
        echo "Markdown documentation is up to date ✓"

    - name: Upload manpage patch artifact
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: manpage-patch
        path: /tmp/manpage.diff
        if-no-files-found: error

    - name: Upload markdown patch artifact
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: markdown-patch
        path: /tmp/markdown.diff
        if-no-files-found: error

  report:
    name: git-perf
    if: always()
    needs: [test, rustfmt, clippy, rustdoc, manpage-check]
    uses: ./.github/workflows/report.yml
    with:
      additional-args: '-s rust'
      concurrency-token: gh-pages-${{ github.ref }}
      release: 'branch'
      audit-args: '-m report -m report-size -s os="ubuntu-22.04" -s rust="stable" --min-measurements 10'
