name: ci

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  pull-requests: write

on:
  push:
    branches:
      - master
      - build/*
  pull_request:
    branches:
      - master
jobs:
  test:
    name: test
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - stable
        - beta
        include:
        - build: stable
          os: ubuntu-22.04
          rust: stable
        - build: beta
          os: ubuntu-22.04
          rust: beta
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 40

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}

    - name: Install libfaketime
      run: |
        if [[ $(uname -s) = Darwin ]]; then
          brew install libfaketime
        else # ubuntu
          sudo apt-get install libfaketime
        fi

    - name: Install nextest
      uses: taiki-e/install-action@nextest

    - name: Build git-perf
      run: cargo build --verbose

    - name: Run tests
      run: cargo nextest run --verbose

    - name: Run fibonacci benchmarks and track performance
      env:
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      run: |
          set -x
          # Install cargo-criterion for JSON output support
          cargo install cargo-criterion --version 1.1.0 --locked

          # Run fibonacci benchmark with JSON output
          cargo criterion --bench sample_ci_bench --message-format json > bench-results.json || true

          # Import benchmark results
          if [ -s bench-results.json ]; then
            cargo run -- import criterion-json bench-results.json \
              --metadata ci=true \
              --metadata workflow="${GITHUB_WORKFLOW}" \
              --metadata os=${{matrix.os}} \
              --metadata rust=${{matrix.rust}}

            # Push imported measurements
            git push origin refs/notes/perf-v3 || true

            # Audit fibonacci benchmarks (using mean statistic)
            # Allow up to 10 sigma deviation to account for CI variability
            cargo run -- audit -n 40 -m "bench::fibonacci_10::mean" -s os=${{matrix.os}} -s rust=${{matrix.rust}} --min-measurements 3 --sigma 10 || echo "Fibonacci 10 audit failed (expected on first runs)"
            cargo run -- audit -n 40 -m "bench::fibonacci_20::mean" -s os=${{matrix.os}} -s rust=${{matrix.rust}} --min-measurements 3 --sigma 10 || echo "Fibonacci 20 audit failed (expected on first runs)"
          else
            echo "No benchmark results to import"
          fi

    - name: Run sample perf measurements
      env:
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      run: |
          set -x
          cargo install --path git_perf
          # Run report on repo with known (n=10) number of measurements
          git perf measure -n 10 -m test-measure2 -k os=${{matrix.os}} -k rust=${{matrix.rust}} -- sleep 1
          git perf measure -n 10 -m report -k os=${{matrix.os}} -k rust=${{matrix.rust}} -- git perf report -n 1 -o report.html
          git perf add -m report-size -k os=${{matrix.os}} -k rust=${{matrix.rust}} $(wc -c < report.html)
          git perf push

          git perf audit -n 40 -m test-measure2 -s os=${{matrix.os}} -s rust=${{matrix.rust}} --min-measurements 10
          git perf audit -n 40 -m report -s os=${{matrix.os}} -s rust=${{matrix.rust}} --min-measurements 10
          git perf audit -n 40 -m report-size -s os=${{matrix.os}} -s rust=${{matrix.rust}} --min-measurements 10

    - name: Archive report
      uses: actions/upload-artifact@v5
      if: always()
      with:
        include-hidden-files: true
        name: report-${{matrix.os}}-${{matrix.rust}}.html
        path: report.html
        if-no-files-found: error

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all --check

  clippy:
    name: clippy
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - name: Run clippy
      run: cargo clippy -- -D warnings

  rustdoc:
    name: rust doc
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt
    - name: Check docs
      run: |
        export RUSTDOCFLAGS="-D warnings"
        cargo doc --no-deps

  documentation-check:
    name: Check documentation is up to date
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Generate documentation
      run: |
        ./scripts/generate-manpages.sh
    - name: Check for uncommitted changes
      run: |
        if ! git diff --exit-code man/ docs/; then
          echo "Error: Documentation is out of date!"
          echo "Please run './scripts/generate-manpages.sh' and commit the changes."
          echo ""
          echo "Diff:"
          git diff man/ docs/
          exit 1
        fi
        echo "Documentation is up to date ✓"

  report:
    name: git-perf
    runs-on: ubuntu-22.04
    if: always()
    needs: [test, rustfmt, clippy, rustdoc, documentation-check, release-binary-size]
    concurrency:
      group: gh-pages-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 40

      - uses: ./.github/actions/report
        with:
          depth: 40
          additional-args: '-s rust'
          audit-args: '-m report -m report-size -m release-binary-size -s os="ubuntu-22.04" -s rust="stable" --min-measurements 10'
          git-perf-version: 'branch'
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release-binary-size:
    name: release-binary-size
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 40

    - name: Install Rust (stable)
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Build optimized git-perf binary
      run: cargo build --locked --release -p git-perf

    - name: Measure binary size and push metric
      env:
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      run: |
        set -euo pipefail
        BIN=target/release/git-perf
        if [ ! -f "$BIN" ]; then
          echo "Binary not found at $BIN" >&2
          ls -la target/release || true
          exit 1
        fi
        BYTES=$(stat -c%s "$BIN")
        mkdir -p metrics
        echo "$BYTES" > metrics/release_binary_size.txt
        ./target/release/git-perf add -m release-binary-size -k os=ubuntu-22.04 -k rust=stable "$BYTES"
        ./target/release/git-perf push

    - name: Audit release binary size
      run: |
        ./target/release/git-perf audit -n 40 -m release-binary-size -s os=ubuntu-22.04 -s rust=stable --min-measurements 10

    - name: Upload size artifact
      uses: actions/upload-artifact@v5
      with:
        name: release-binary-size
        path: metrics/release_binary_size.txt
