name: Publish Check

on:
  pull_request:
    branches: [ master ]

jobs:
  publish-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Check cargo publish (dry-run)
        run: |
          # Verify both packages can be packaged and published
          # Order matters: cli_types has no workspace deps, git-perf depends on cli_types

          # First, package both to verify they can be bundled correctly
          cargo package --package git_perf_cli_types --allow-dirty
          cargo package --package git-perf --allow-dirty

          # Verify cli_types can be published (no workspace dependencies)
          cargo publish --dry-run --package git_perf_cli_types --allow-dirty

          # For git-perf: use --no-verify to skip the build check that would fail
          # when cli_types has unpublished changes. The cargo package above already
          # verified the package builds correctly with path dependencies.
          cargo publish --dry-run --package git-perf --allow-dirty --no-verify
