name: 'git-perf report'
on:
  workflow_call:
    inputs:
      release:
        description: 'release to install (`latest` or `branch`)'
        required: false
        type: string
        default: 'latest'
      concurrency-token:
        description: 'token to prevent concurrent updates of github pages'
        required: false
        type: string
        default: 'gh-pages-concurrency'
      depth:
        description: 'depth of the report in number of commits'
        required: false
        type: number
        default: 40
      additional-args:
        description: 'additional arguments to git-perf report invocation'
        required: false
        type: string
        default: ''
      audit-args:
        description: 'additional arguments to git-perf audit invocation'
        required: false
        type: string
        default: ''


permissions:
  pages: write
  contents: write
  pull-requests: write

concurrency:
  group: ${{ inputs.concurrency-token }}

jobs:
  report:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: ${{ inputs.depth }}

      - name: Generate and publish report (from branch)
        if: ${{ inputs.release == 'branch' }}
        uses: ./.github/actions/report
        with:
          depth: ${{ inputs.depth }}
          additional-args: ${{ inputs.additional-args }}
          audit-args: ${{ inputs.audit-args }}
          git-perf-version: ${{ inputs.release }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate and publish report (from release)
        if: ${{ inputs.release != 'branch' }}
        uses: kaihowl/git-perf/.github/actions/report@master
        with:
          depth: ${{ inputs.depth }}
          additional-args: ${{ inputs.additional-args }}
          audit-args: ${{ inputs.audit-args }}
          git-perf-version: ${{ inputs.release }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
