name: Test dotfiles

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 41 11 * * 0
jobs:

  build:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Install and test
        shell: bash
        run: |
          ./test.sh
          export PATH=$(pwd):$PATH
          git perf measure -n 10 -m test-measure -kv os=${{matrix.os}} sleep 0.01
          git perf push
          git perf audit -m test-measure -s os=${{matrix.os}}

