name: Test git-perf

# TODO(kaihowl) deeper test with merge-based PR workflow (HEAD == merge commit)

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - build/*
  pull_request:
    branches:
      - master
  schedule:
    - cron: 41 11 * * 0
jobs:

  build:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          # TODO(kaihowl) is there an off-by one?
          fetch-depth: 41
      - name: test
        shell: bash
        run: |
          git show HEAD

