name: Test dotfiles

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 41 11 * * 0
jobs:

  build:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install and test
        shell: bash
        run: |
          ./measure.sh ${{ matrix.os }}

